config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create] do
    resource :following_relationship, only: [:create, :destroy]
  end
  resources :shouts, only: [:create]
  resources :text_subjects, only: [:create]
  resources :image_subjects, only: [:create]
  resource :search, only: [:show]
  get "/sign_up", to: "users#new"

  constraints Monban::Constraints::SignedIn.new do
    get "/", to: "dashboards#show", as: :dashboard
    resource :following, only: [:show]
    resource :followers, only: [:show]


  end
  root to: "sessions#new"

  get "/:username", to: "users#show", as: :user
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

  validate :user_is_not_following_themselves

  private

  def user_is_not_following_themselves
    if follower_id == followed_user_id
      errors.add(:base, "Users cannot follow themselves")
    end
  end
end

app/models/image_subject.rb
class ImageSubject < ActiveRecord::Base
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, polymorphic: true

  def body=(new_body)
    self[:body] = new_body.upcase
  end
end

app/models/text_subject.rb
class TextSubject < ActiveRecord::Base
  belongs_to :shout

  belongs_to :user

  def body=(new_body)
    self[:body] = new_body.upcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, uniqueness: true, presence: true

  has_many :text_subjects

  has_many :shouts

  has_many :text_subjects,
    through: :shouts

  has_many :followed_user_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :follower_id

  has_many :followed_users,
    through: :followed_user_relationships

  has_many :follower_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :followed_user_id

  has_many :followers,
    through: :follower_relationships

  def follow(other_user)
    followed_users << other_user
  end

  def unfollow(other_user)
    followed_users.destroy(other_user)
  end

  def following?(other_user)
    followed_user_ids.include?(other_user.id)
  end

  def timeline
    Shout.where(user_id: followed_users).order(created_at: :desc)
  end

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_action :require_login

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_subject = TextSubject.new
    @image_subject = ImageSubject.new
    @timeline = current_user.timeline.page params[:page]
    @all_shouts = Shout.all.order(created_at: :desc)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def show
    @followers = current_user.followers
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    followed_user = User.find_by!(username: params[:user_id])
    current_user.follow(followed_user)
    redirect_to :back
  end

  def destroy
    followed_user = User.find_by!(username: params[:user_id])
    current_user.unfollow(followed_user)
    redirect_to :back
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def show
    @users = current_user.followed_users
  end
end

app/controllers/image_subjects_controller.rb
class ImageSubjectsController < ApplicationController
  def create
    image_subject = ImageSubject.create(image_subject_params)
    current_user.shouts.create(subject: image_subject)
    redirect_to :dashboard
  end

  private

  def image_subject_params
    params.require(:image_subject).
      permit(
        :url,
    )
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search_results = User.where("username LIKE ?", "%#{params[:query]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).
     permit(
       :email,
       :password,
    )
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    @shout = current_user.shouts.create(shout_params)
    redirect_to :dashboard
  end

  private

  def shout_params
    params.require(:shout).
      permit(
        :body,
    )
  end
end

app/controllers/text_subjects_controller.rb
class TextSubjectsController < ApplicationController
  def create
    text_subject = TextSubject.create(text_subject_params)
    current_user.shouts.create(subject: text_subject)

    redirect_to :dashboard
  end

  private

  def text_subject_params
    params.require(:text_subject).
      permit(
        :body,
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:show, :new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find_by!(username: params[:username])
    @shouts = @user.shouts.order(created_at: :desc).page params[:page]
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).
      permit(
        :email,
        :password,
        :username,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if target.errors.present? %>
  <p>Form could not be submitted because:</p>
  <ul>
    <% target.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/dashboards/show.html.erb
<h1>Shoutr</h1>

<div>
  <%= link_to current_user.username, current_user %>

  <%= form_tag "/search", method: "get" do %>
    <%= label_tag :query, "Search for user..." %>
    <%= text_field_tag :query %>
    <%= submit_tag "Search" %>
  <% end %>

  <ul>
    <li><%= link_to "Followers", :followers %></li>
    <li><%= link_to "Following", :following %></li>
  </ul>
</div>

<%= form_for @text_subject do |form| %>
  <%= form.text_area :body, placeholder: "Shout some words!" %>
  <%= form.submit "Shout" %>
<% end %>

<%= form_for @image_subject do |form| %>
  <%= form.text_field :url, placeholder: "Shout image URL:" %>
  <%= form.submit "Shout" %>
<% end %>

<ul>
  <%= render @timeline %>
</ul>

<%= paginate @timeline %>

What other people are shouting:
<ul>
  <%= render @all_shouts %>
</ul>

app/views/followers/show.html.erb
<h2>Followers</h2>

<%= render @followers %>

app/views/followings/show.html.erb
<ul>
  <%= render @users %>
</ul>

app/views/image_subjects/_image_subject.html.erb
<p><%= image_tag image_subject.url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutr</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
  <p>You are currently signed in as <%= current_user.username %>. <%= link_to "Sign out?", session_path, method: :delete %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/searches/show.html.erb
<%= render @search_results %>

app/views/shouts/_shout.html.erb
<li>
  <%= render shout.subject %>
  <%= link_to shout.user.username, shout.user %>
  shouted
  <%= time_ago_in_words(shout.subject.created_at) %>
  ago
</li>

app/views/text_subjects/_text_subject.html.erb
<p><%= text_subject.body %></p>

app/views/users/_follow_button.html.erb
<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= button_to "Unfollow #{user.username}", [user, :following_relationship], method: :delete %>
  <% else %>
    <%= button_to "Follow #{user.username}", [user, :following_relationship] %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username, user %>
  <%= render "users/follow_button", user: user %>
</li>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= render "errors", target: @user %>
  </div>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <%= @user.username %>
  <%= render "follow_button", user: @user %>

  <ul>
    <%= render @shouts %>
  </ul>
  <%= paginate @shouts %>
</div>